### PR TITLE
libretro: Fix build failure with clang.

### PR DESCRIPTION
**Pull request by orbea**
@byuu For either standalone or libretro on linux do you support gcc, clang or both?

This fixes the following build issue with the libretro target and `clang-9.0.0`. The basic problem is that the libretro GNUmakefile is not correctly using `$(options)` like the bsnes target and misses `-fopenmp`.

```
clang++ -o out/bsnes_libretro.so -shared obj/libretro.o obj/libco.o obj/emulator.o obj/filter.o obj/lzma.o obj/sfc-interface.o obj/sfc-system.o obj/sfc-controller.o obj/sfc-cartridge.o obj/sfc-memory.o obj/sfc-cpu.o obj/sfc-smp.o obj/sfc-dsp.o obj/sfc-ppu.o obj/sfc-ppu-fast.o obj/sfc-expansion.o obj/sfc-coprocessor.o obj/sfc-slot.o obj/gb-apu.o obj/gb-camera.o obj/gb-display.o obj/gb-gb.o obj/gb-joypad.o obj/gb-mbc.o obj/gb-memory.o obj/gb-printer.o obj/gb-random.o obj/gb-rewind.o obj/gb-save_state.o obj/gb-sgb.o obj/gb-sm83_cpu.o obj/gb-symbol_hash.o obj/gb-timing.o obj/processor-arm7tdmi.o obj/processor-spc700.o obj/processor-wdc65816.o -Wl,--no-undefined -Wl,--version-script=target-libretro/link.T -Wl,-Bdynamic -lpthread -ldl -lgomp
/usr/bin/ld: obj/sfc-ppu-fast.o: in function `SuperFamicom::PPUfast::Line::flush()':
bsnes/bsnes/sfc/ppu-fast/line.cpp:4: undefined reference to `__kmpc_global_thread_num'
/usr/bin/ld: bsnes/bsnes/sfc/ppu-fast/line.cpp:7: undefined reference to `__kmpc_fork_call'
/usr/bin/ld: bsnes/bsnes/sfc/ppu-fast/line.cpp:7: undefined reference to `__kmpc_serialized_parallel'
/usr/bin/ld: bsnes/bsnes/sfc/ppu-fast/line.cpp:7: undefined reference to `__kmpc_end_serialized_parallel'
/usr/bin/ld: obj/sfc-ppu-fast.o: in function `.omp_outlined.':
bsnes/bsnes/sfc/ppu-fast/line.cpp:8: undefined reference to `__kmpc_global_thread_num'
/usr/bin/ld: obj/sfc-ppu-fast.o: in function `.omp_outlined._debug__':
bsnes/bsnes/sfc/ppu-fast/line.cpp:8: undefined reference to `__kmpc_for_static_init_4u'
bsnes/bsnes/sfc/ppu-fast/line.cpp:7: undefined reference to `__kmpc_for_static_fini'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [target-libretro/GNUmakefile:13: all] Error 1
```

Please note:

* I also fixed the name so its actually used and reduces hardcoding in the GNUmakefile.
* I only touched the linux code path since that is all I can test. Other platforms probably can use similar fixes and the platform detection probably can be removed in this file to correctly use `$(options)` too.

### CODE REVIEW

**Comment by byuu** [comment]
@rtretiakov review please?

**Comment by rtretiakov** [comment]
-Wl,--no-undefined is what breaks clang builds, and why it's not in the link stage of the macOS build.
There is definitely some room to optimize the libretro makefile, and the general spirit of this change is the right direction, but I can't give a meaningful response until this weekend due to real life overload.

**Comment by orbea** [comment]
> I can't give a meaningful response until this weekend due to real life overload.

No rush, real life is more important.

> -Wl,--no-undefined is what breaks clang builds

I think I was overzealous and added back the `-Wl,--no-undefined -Wl,--version-script=target-libretro/link.T` and the build still works here with both clang and gcc.

**Comment by byuu** [comment]
I merged most of this ($(name) portion) except for the flags. Just ping me when we've decided on the flags please.

**Pull request closed without merging**
