### PR TITLE
libretro: Add libretro libraries to gitignore.

### PR DESCRIPTION
**Pull request by orbea**
I nearly added the libretro library to my previous PR and this will prevent such mistakes in the future. From the current `target-libretro/GNUmakefile` it seems all of the libretro libraries will end in `.so`, `.dll` or `.dylib`. Also this fixes fully cleaning the repo with `git clean -xdf` after building libretro.

### CODE REVIEW

**Comment by byuu** [comment]
I'd rather not do this, since it doesn't apply to the main bsnes release, sorry.

**Comment by Screwtapello** [comment]
The `make clean` target handles both bsnes and the libretro core because it just blows away everything in the `out/` directory, while the `.gitignore` file is more cautious and only ignores things on a blacklist.

Would you take a patch that makes the .gitignore file match the "ignore everything" logic of `make clean`?

**Comment by orbea** [comment]
@Screwtapello 

Yes, but try this.
```
make target=bsnes

# after it builds
git add .
git commit -m test
# there will be nothing to commit
```
```
make target=libretro

# after it builds
git add .
git commit -m test
# the libretro library will have been committed and this can sneak into a commit without being noticed
```

**Comment by Screwtapello** [comment]
@orbea Yeah, I know, I'm trying to see if there's a way to solve your problem that byuu would be comfortable with.

**Comment by orbea** [comment]
I think the least disruptive method is to update the `.gitignore` like in this PR since its very unlikely anyone would want to commit any binary files to the `out/` directory. Another idea would be to make a second `out/` directory for only libretro and add the `.gitignore` there, but seems far less trivial and uglier.

But if byuu doesn't want it that's fine. :shrug:

**Pull request closed without merging**
