### PR TITLE
HD Mode 7 improvements (perspective detection and extbg) [2nd try]

### PR DESCRIPTION
**Pull request by DerKoun**
Some necessary cleanup and multiple removals since the last try resulted in the following 3 commits:
- The code that determines the Mode 7 line groups and interpolation lines for perspective correction moved to 'line' and is now only called only once per frame. (I tried to have the code in 'mode7hd' and only call it from 'line', but C++ hates me, so I put it directly in "flush()" for now.)
- Added simple perspective detection to the code from the previous commit. A group is considered to not have perspective when any of the scale values both increases and decreases between lines. To keep the settings as-is there currently is only 'off' and 'auto', no 'forced'.
- EXTBG Mode 7 foreground priorities are now handled in HD (fixing artifacts in "Mohawk and Headphone Jack").

Comments and variable names have improved. So I hope the code is clearer now. If not, let me now.

### CODE REVIEW

**Comment by byuu** [comment]
Thanks for being so patient with the backporting here, much appreciated!

We'll start with the easiest one, the EXTBG fix. It doesn't feel entirely like a proper fix to just move BG2 rendering to after OBJ rendering ... that feels very game-dependent. BG1 priority is 3, BG2 priorities are 1,5. OBJ priorities are 2,4,6,8. Meaning the order of operations here really needs to be independent.

I take it that the HD mode 7 plotting code isn't going great here.

Well, because this change will only affect HD mode 7, I'm okay making it as a temporary workaround as this one's a tough issue. But we should note that while it'll fix Mohawk, it could very well break another EXTBG mode game (if one even exists), or perhaps some homebrew in the future.

**Comment by DerKoun** [comment]
I assumed that without HD the order in which the renderBackground/Object methods are called is irrelevant, as the priorities for each pixel ensure the right layer renders the pixel color. Please correct me if I'm wrong there.
The issue here is caused by 'plotHD' only comparing the priority of 1 pixel before rendering a 'scale'-by-'scale' square of them.
The simple and complete solution would of course be to check each of these pixels. But I had decided against that as an optimization (and because at that point I did not know Mohawk as a test case).
So I thought that moving the method, that does check the priority for each pixel (i.e. renderBackground(bg2)), to the end, would solve the issue with no side effects. 
Please let me know if I missed or oversimplified something. Ideally, could you describe a hypothetical scenario where this changes has a negative effect? I'd really like to understand, so thanks for your patience with the new guy.

**Comment by byuu** [comment]
Even just for BG1 (with or without EXTBG), sprites can be placed behind the background, so if the BG/OBJ layers aren't properly respecting the pixel priority buffers, it's possible more games will be affected.

I've merged this as a workaround for now and added a comment. It's better to fix the game for now than leave it broken, but I hope by doing this we don't end up having it stay incomplete, ahah ^-^;  I don't really have the bandwidth to work on a better solution right now that won't hurt performance, though ^^;

**Comment by byuu** [comment]
I hope you don't mind, but I've decided to push v108 now, on the off chance these changes cause any regressions, to avoid needing time for additional beta testing. We'll get nightlies published soon so people can try out these additional HD mode 7 improvements soon ^-^

**Comment by DerKoun** [comment]
Sure. You're much more qualified to judge the risks of features, especially for stable releases. I know why I stick with betas, it'll be my eternal excuse...

**Comment by Screwtapello** [comment]
@DerKoun, could you please rebase your changes onto the latest master? The conflicts seem to be incredibly minor, and it'd be a shame to leave this languishing.

**Comment by DerKoun** [comment]
Merged byuus partial merge back into the PR (if that makes sense). Should be good again?

**Comment by byuu** [comment]
My apologies for taking a while on this. Been really busy with site updates and the math involved with this is a bit intimidating for me ... but I promise I will get to it and merge it in. Thank you again for your help here, I do really appreciate it! I'll hold v109 until these changes are merged.

**Comment by DerKoun** [comment]
I didn't consider the code complex, but I'm not that good at writing code others can maintain. (working on that.)
Feel free to ask any questions. big or small. at any time.

**Comment by byuu** [comment]
https://github.com/byuu/bsnes/commit/1195c46ac00eb7f0da057e8c4f6cd1d4b2651c6e

I'm sorry this took so long to merge. I reformatted the code a bit instead of directly merging. I moved the perspective group caching to mode7hd.cpp, and I also made it not get called when HD mode 7 isn't enabled so that it won't impact performance when disabled.

Please let me know if I screwed anything up when merging this ^-^;;

Thank you for your patience and for your help with this awesome feature!! :D

**Pull request closed without merging**
