### PR TITLE
ruby/macOS: implement joypad support

### PR DESCRIPTION
**Pull request by Sintendo**
Tested and confirmed working with the following devices:
- iBuffalo Classic USB Gamepad
- Microsoft Xbox 360 wired controller (using [this driver](https://github.com/360Controller/360Controller/releases/tag/v0.16.11))
- Nintendo Switch Pro Controller (Bluetooth)

References:
- https://github.com/dolphin-emu/dolphin/tree/828dc0f204841edac628d1cb5daf72c7ceca4b9f/Source/Core/InputCommon/ControllerInterface/OSX
- https://github.com/libretro/RetroArch/blob/f0046666743e68533790cd6e6697100bfbf9963d/input/drivers_hid/iohidmanager_hid.c
- https://github.com/spurious/SDL-mirror/blob/a52f3654467dcfe7035d1f668d343829402ce24d/src/joystick/darwin/SDL_sysjoystick.c

### CODE REVIEW

**Comment by byuu** [comment]
Oh awesome, thank you! As ruby is ISC-licensed, do I have your permission to use this under the ISC license?

**Comment by Sintendo** [comment]
You have my permission. :+1:

**Comment by byuu** [comment]
I merged this in with a few small changes, please let me know if I screwed anything up and it doesn't work ^-^;;

Also sorry for not direct merging, for some reason when I do that it breaks my GitLab mirroring of this repostiroy >_< I credited you for the work of course ^^;

**Comment by Sintendo** [comment]
Gave it a quick try with my Nintendo Switch Pro controller. Only one hat axis is being picked up.
https://github.com/byuu/bsnes/blob/18d2ab6435fd79d55b3c8b2895d570618afbfe93/ruby/input/joypad/iokit.cpp#L147-L148
Second line should use `y`.

Works as well as my code did otherwise. Thanks for merging.

**Comment by Sintendo** [comment]
You may also want to add a `CFRelease(pageNumber)` in case the second `CFNumberCreate` fails.

https://github.com/byuu/bsnes/blob/18d2ab6435fd79d55b3c8b2895d570618afbfe93/ruby/input/joypad/iokit.cpp#L246-L250

**Comment by byuu** [comment]
Will do, thank you for your help with this.

**Comment by byuu** [comment]
Done, thank you!

**Pull request closed without merging**
