### PR TITLE
target-libretro/GNUMakefile: conditionally enable OpenMP

### PR DESCRIPTION
**Pull request by 5schatten**
LibreELEC or Lakka do not ship OpenMP libs https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-LE9.2/packages/lang/gcc/package.mk#L40 so it would be a nice option if the libretro core would pick up the `openmp` var https://github.com/byuu/bsnes/blob/master/bsnes/GNUmakefile#L4

Beside that I get these warnings because of `'-std=c++17'` & `-fpermissive` flags.
```
cc1: warning: command line option '-std=c++17' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-fpermissive' is valid for C++/ObjC++ but not for C
```

build log:
https://pastebin.com/br3vKvPb

### CODE REVIEW

**Comment by rtretiakov** [comment]
This is going to require deeper thought. While I was porting bsnes to libretro I discovered that you simply need OpenMP for the high resolution Mode 7 support. That means should we make it optional at compile time, we also need the libretro core to hide certain core options related to that.

The comments regarding the Mac in the commit are actually not correct. It does in fact support OpenMP, but does not require those flags when compiling or linking, in fact those will break the build, but it does not mean OpenMP is not supported. At least this is the answer I came to after reading some stackoverflow. It seems you are generally on the right track, but there will still need to be linker rules for the Mac.

I am coming up with a Mac build right now. I do want to fix the warnings when compiling the SameBoy C sources too.

**Comment by 5schatten** [comment]
Well I don't mind to close this if it would break some modes - I'm fine if this topic will be recognized after all ;-)

**Comment by byuu** [comment]
Why are we setting flags=c++17 there anyway? nall/GNUmakefile's implicit build-rule should add the -std appropriate for a given file type, right?

**Comment by rtretiakov** [comment]
@byuu I think that is an artifact left over from early porting work. It does not seem to be necessary, so I will remove it in the pull request I'm about to send over for the Mac build.

**Comment by byuu** [comment]
Sounds good, thank you. I'll merge the other request soon, in the middle of a large-ish higan refactoring.

**Pull request closed without merging**
