### PR TITLE
Ruby alsa fixes

### PR DESCRIPTION
**Pull request by RedDwarf69**
It's not perfect, probably it should use the MMAP interface, but it makes it way better for me.

### CODE REVIEW

**Comment by Screwtapello** [comment]
Have you tested this with and without PulseAudio?

**Comment by RedDwarf69** [comment]
I have tested it with PulseAudio disabled (on my only available computer), supposing anybody wanting to use PulseAudio will use the native backend.

But I have just tested it with PulseAudio... the Dynamic Rate Control, with a given latency, unsurprisingly works worse, but you can actually play with it set at 100ms and it's not too bad.

FWIW the alsa driver simply fails to initialize() on my computer. I am using
```
--- a/ruby/audio/alsa.cpp
+++ b/ruby/audio/alsa.cpp
@@ -120,7 +120,7 @@ private:
     terminate();
 
     if(!hasDevices().find(self.device)) self.device = hasDevices().first();
-    if(snd_pcm_open(&_interface, self.device, SND_PCM_STREAM_PLAYBACK, SND_PCM_NONBLOCK) < 0) return terminate(), false;
+    if(snd_pcm_open(&_interface, "default"/*self.device*/, SND_PCM_STREAM_PLAYBACK, SND_PCM_NONBLOCK) < 0) return terminate(), false;
 
     uint rate = self.frequency;
     uint bufferTime = self.latency * 1000;
```
to "fix" the issue. But I have not really tried to understand what the real issue is.

**Comment by RedDwarf69** [comment]
Sorry, I had used my employer email address. I have force pushed it with my personal one, haven't changed anything in the code.

**Comment by Screwtapello** [comment]
I built this branch myself, then launched bsnes with `pasuspender bsnes/out/bsnes`. In the Drivers pane of the Settings dialog, I changed the driver to "ALSA" and the device to "sysdefault:CARD=PCH" (because "default" would be the PulseAudio backend on my system, defeating the point). The default latency was 20ms.

I watched the scrolling intro of *Lufia and the Fortress of Doom", and heard a few glitches, each about 38 seconds apart. Bumping the latency to 100ms didn't get rid of all of them, but if I turn off video sync and dynamic rate control, then turn on audio sync, the ALSA driver produces perfect sound at 100ms and nearly perfect sound at 20ms.

If I turn off dynamic rate control and turn on both video sync and audio sync, at 20ms latency it's pretty much as good as with only audio sync - one small glitch every 40-50 seconds.

I'd love to hear other people's experiences.

**Comment by RedDwarf69** [comment]
A problem I have is that with DRC it uses more CPU, which basically leaves me without any. So I have audio glitches because of a lack of CPU, not because (at least not only) a problem with the alsa DRC implementation.

I will comment further once https://github.com/byuu/bsnes/issues/289 is clarified.

**Comment by RedDwarf69** [comment]
So I have been playing with it a bit more and I have just understood where my problems come from. The second I enable video sync my framerate drops from 60 to 58 fps. This is massive, and the 0.005 resampler maxDelta is not enough to compensate it. I don't have audio glitches every 40-50 seconds, I have problems every 2 seconds. But increasing the maxDelta makes my problems go away.

Now, `xrand` tells me the monitor refresh rate it 59.96. And retroarch fps counter seems to agree. But with bsnes I get the 58fps with either OpenGL 2.0 or 3.2 (XVideo video sync doesn't work at all). Has anybody ever seen anything similar?

**Comment by byuu** [comment]
I merged this in, thank you so much! Sorry for the delay ^^;

Also, I added a timeout to the while(true) loop inside level. If it fails 256 times in a row, I give up so the program can't dead-lock. I don't know if 256 is too high or too low, but certainly we should have some kind of timeout there just in case. Since I don't have Linux to test with myself, please send another pull request if the value I randomly chose isn't a good one ^-^;;

**Pull request closed without merging**
