### PR TITLE
(if not wrong) set region and fps in the libretro core

### PR DESCRIPTION
**Pull request by Pixelnarium**
I don't know if it is necessary but currently the core always reports an NTSC game with flat 60Hz. [In the higan core](https://github.com/libretro/higan/blob/libretro-v094/target-libretro/libretro.cpp#L563) it was set to their original values based on the game. Or does the core internally handles DRC?

I read that bsnes now always resamples to 48kHz so I did not touch that setting. It that the case with the core too?

### CODE REVIEW

**Comment by byuu** [comment]
Does RA actually use this field? The reason I took out frame rate reporting from my own cores is because it's not accurate. Toggling interlace changes the frame rate. Other systems (especially handhelds) have variable refresh rates.

**Comment by Pixelnarium** [comment]
Well yes. I am not an expert on this but if you start up PAL games and tell RetroArch to run them at 60Hz can lead to trouble. I think RetroArch runs them at 60Hz then.

With this "fix" RetroArch tells me that:
> [INFO] [Video]: Timings deviate too much. Will not adjust. (Display = 59.94 Hz, Game = 50.01 Hz)

Maybe @rtretiakov knows more on that? I am not involved in any RetroArch/libretro development.

bsnes has the same problem btw. If I use the DRC path and start up a PAL game bsnes runs them at 60Hz with audio errors. bsnes only runs them at 50Hz when I disable DRC and only enable audio sync.

**Comment by rtretiakov** [comment]
I have been attempting to figure this issue out for the last couple of days without any luck. RetroArch does not seem to call retro_get_region, therefore I am not sure if that method was deprecated or is meant to be used internally by a core. PAL games sometimes will not run at all, sometimes have video errors, or kick you to an incorrect region screen as can be seen with Terranigma (E). I tried manually setting the timings but still no luck, and was hoping to analyze bsnes deeper to see what is being logically done differently in byuu's frontend code. I am happy to see someone else is also working on this issue.

**Comment by byuu** [comment]
rtretiakov, if you'd like to chat with me on some messaging service, I'll walk you through the bsnes side of things: how it determines regions, etc. I'll need your input for the Retroarch side of things, but I think together we can figure out a good fix. If you're interested, let me know.

**Comment by rtretiakov** [comment]
@byuu I think it's fine to merge this pull request. I am manually using it in my own environment and it does actually improve things, there is nothing wrong here. It does not fix PAL games, but it does fix some frame timing issues and will still be necessary when the real PAL game issue is solved. I've also had a mutual contact reach out to you so we can establish private communications.

**Comment by rtretiakov** [comment]
I've got it now, it was a simple one line fix on top of the changes by @Pixelnarium. I'll make a new pull request.

**Comment by byuu** [comment]
Superseded by subsequent patch, but thank you all the same.

**Pull request closed without merging**
