### PR TITLE
HD Mode 7 improvements (incl. perspective detection)

### PR DESCRIPTION
**Pull request by DerKoun**
As per #11, this collects all HD Mode 7 improvements between bsnes-hd beta 3 and 8:

- perspective correction auto detect (simple, but works quite well)
- super-sampling at any scale
- 1x scale
- additional mosaic mode: 1x scale
- HD extbg "Mode 7 foregrounds" fixed
- some perspective correction code moved to 'line' to only do it once per frame (needs some cleanup, sorry)

This was done rather quickly between other stuff, so if there are any issues or question, just let me know.

If putting this here helps: I'm fine with the merged code being put under a different open source license. (And we can talk about commercial licensing if that ever comes up.)

### CODE REVIEW

**Comment by byuu** [comment]
Oh wow, I'm very appreciative of this, but that is a whole lot of very difficult to understand code.

I was thinking this would be a small "true/false" determination for whether to disable perspective correction when it would cause problems in certain games, preferably with as few false-positives as was practical.

I'm not sure a pull request is going to be a good format for this. Maybe we should talk elsewhere and work through these one by one. Would you be up for that?

**Comment by DerKoun** [comment]
I'll update the pull request with comments added to the code (with hashtags to easily find them and later edit or remove them). Maybe that will be all the help you need. If not it'll at least give us anchor-points to better discuss the code. If you prefer, at that point, we can move this, e.g. to Discord. The time zone difference is 7 hours (Europe - Japan), so weekend would be my preference.

**Comment by DerKoun** [comment]
Added comments. Hope that those help:

#HDupdate1perspDetect   perspective correction auto detect
#HDupdate2scaledSampl   super-sampling at any scale
#HDupdate3scaleOne      1x scale
#HDupdate4moasaicOne    additional mosaic mode: 1x scale
#HDupdate5foregrFix     HD extbg "Mode 7 foregrounds" fixed
#HDupdate6perspLine     some perspective correction code moved to 'line' to only do it once per frame
#HDupdate7other         other

**Comment by Screwtapello** [comment]
I'm not byuu, so take this with a grain of salt, but... it'd be a lot easier to understand what's going on if this were a series of 7 commits that each made a single change, rather than one commit with all the changes mixed in together.

It's nice to have comments that annotate what change each feature is part of, but byuu's going to want to remove them before merging the code, and then that information will be lost. If they were separate commits, that information would be preserved in the git history.

Just in case you're not aware, byuu, when looking at the "Files changed" tab of a PR, if you hover the mouse over a modified line, a "+" button appears at the left; if you click it, you can add a comment about that line in particular, and have a little conversation about each change individually in-context rather than trying to discuss the whole thing in top-level comments like this one.

**Comment by byuu** [comment]
Of the changes added here:
* perspective correction detect is definitely desired, especially if it disables it when bad
* super sampling was meant to match the SNES resolution and look "native", I don't think it's highly useful to be able to supersample above it ... using the non-super sampled version seems the better option there
* I don't understand the 1x scale change. Why would we want that?
* more complexity for mosaic with 1x scale, makes it even less desirable?
* EXTBG fix is important, I thought we already fixed Mohawk & Headphone Jack though, guess not ^^;
* optimizing the perspective code to once per frame sounds fun
* other sounds vague ^-^;
Would agree with Screwtape, one request at a time is probably best. I don't want to make you jump through hoops to help though, we can take the chat to Discord and work through the pull request.

**Comment by DerKoun** [comment]
(I thought I had posted this 10h ago, but apparently failed.)

- perspective correction detection: A Mode 7 line group is considered to have perspective, unless there is both a pair of sequential lines where one of the scale factors increases and also one where the same one decreases. The code is in 'line' at the Mode 7 group code I pulled out (see below).
- super sampling can be used as anti-aliasing, but practically it is too expensive and not much use for most bsnes users. I'll remove it from this pull request.
- 1x scale is only required to get back the old super-sampling (and for HD features not upstreamed). So I'll remove that as well.
- Making Mosaic lines 1x scale is a compromise between going full SD Mosaic and not doing Mosaic at all (also it works with widescreen, which does not matter to bsnes at this point). I'll remove it for now, for simplicity (and as it only affects very view games/scenes).
- The EXTBG foreground issue is noticeable in Mohawk when there is a foreground mesh fence (and you look closely). The priorities are handled in SD. The fix is literary just 2 lines, swapping the render order.
- The code moved from Mode 7 HD to 'line' is also the place where I added the perspective detection, so it would be convenient to keep. It is just about finding the lines where the Mode 7 groups start and end as well as picking the lines between which to interpolate. The latter are slightly inside the groups, as there may be lines at the edges of the groups that are erroneous (or at least different in ways I don't understand) and those should not break the perspective interpolation. The "width" setting could be removed, always using narrow to be save. The slightly less accurate perspective correction should not be that noticeable. Then correction could be a boolean setting again (off/auto). I'll add that simplification. It can later be changed again if necessary.
- "other" is 2 functioned I set to inline as it seems to help HD performance and a slightly improved check for whether a line is Mode 7.

With the removals and simplification I think the pull request will match your intentions for bsnes much better. I think the settings dialog may be down to zero changes.

I'll also tweak the comments so they can stay in (remove hashtags and make them about the code, not about the change), split it into commits and try to refactor at least the worst variable and member names. These are hoops of my own making, so to speak. (At work my colleagues and I teach the apprentices to write code that is readable and maintainable for others. I did not do that in this project.) So fixing them is a good exercise for me and improves the code quality in my project. I won't have time today, so I'll most likely update the pull request tomorrow (Friday) or Saturday.

**Comment by DerKoun** [comment]
I made some mistakes in my fork, still trying to figure out some details of GitHub, I'll start a new pull request over the weekend

**Pull request closed without merging**
